version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:bf:69:46:c7:3e:b6:50:29:10:33:44:d1:57:49:a5"
            - "00:7e:cb:53:3e:b5:0d:74:0a:5d:61:45:02:b8:ec:71"
            - "f1:2b:28:6e:f9:2d:9a:92:69:14:6b:bf:9d:09:a1:8c"
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get --assume-yes install texlive-latex-recommended
      - run: pdflatex resume_EN.tex
      - run: git config --global user.email circleci@circleci
      - run: git config --global user.name CircleCI
      - run: git clone git@github.com:miguel-vila/miguel-vila.github.io.git
      - run: mv resume_EN.pdf miguel-vila.github.io/
      - run: cd miguel-vila.github.io && git add resume_EN.pdf
      - run: cd miguel-vila.github.io && git commit -m "resume updated [ci skip]"
      - run: cd miguel-vila.github.io && git push origin master
